{"uid":"858fc8a225486f1","name":"test_multiplicacion","fullName":"test_demo#test_multiplicacion","historyId":"b3795b78bcde85f1a4845c4133e9c10b","time":{"start":1756389183648,"stop":1756389183648,"duration":0},"status":"failed","statusMessage":"AssertionError: Multiplicación incorrecta: 3*4 debería ser 15, pero fue 12\nassert 12 == 15","statusTrace":"def test_multiplicacion():\n        a, b = 3, 4\n    \n        with allure.step(\"Multiplicando los valores\"):\n            resultado = a * b\n            allure.attach(str(resultado), name=\"Resultado parcial\", attachment_type=allure.attachment_type.TEXT)\n    \n        with allure.step(\"Verificando el resultado\"):\n            esperado = 15\n>           assert resultado == esperado, f\"Multiplicación incorrecta: {a}*{b} debería ser {esperado}, pero fue {resultado}\"\nE           AssertionError: Multiplicación incorrecta: 3*4 debería ser 15, pero fue 12\nE           assert 12 == 15\n\ntest_demo.py:46: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError: Multiplicación incorrecta: 3*4 debería ser 15, pero fue 12\nassert 12 == 15","statusTrace":"def test_multiplicacion():\n        a, b = 3, 4\n    \n        with allure.step(\"Multiplicando los valores\"):\n            resultado = a * b\n            allure.attach(str(resultado), name=\"Resultado parcial\", attachment_type=allure.attachment_type.TEXT)\n    \n        with allure.step(\"Verificando el resultado\"):\n            esperado = 15\n>           assert resultado == esperado, f\"Multiplicación incorrecta: {a}*{b} debería ser {esperado}, pero fue {resultado}\"\nE           AssertionError: Multiplicación incorrecta: 3*4 debería ser 15, pero fue 12\nE           assert 12 == 15\n\ntest_demo.py:46: AssertionError","steps":[{"name":"Multiplicando los valores","time":{"start":1756389183648,"stop":1756389183648,"duration":0},"status":"passed","steps":[],"attachments":[{"uid":"a574f1834f9e5041","name":"Resultado parcial","source":"a574f1834f9e5041.txt","type":"text/plain","size":2}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},{"name":"Verificando el resultado","time":{"start":1756389183648,"stop":1756389183648,"duration":0},"status":"failed","statusMessage":"AssertionError: Multiplicación incorrecta: 3*4 debería ser 15, pero fue 12\nassert 12 == 15\n","statusTrace":"  File \"/home/runner/work/qa-e2e/qa-e2e/test_demo.py\", line 46, in test_multiplicacion\n    assert resultado == esperado, f\"Multiplicación incorrecta: {a}*{b} debería ser {esperado}, pero fue {resultado}\"\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":2,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"suite","value":"test_demo"},{"name":"host","value":"pkrvmccyg1gnepe"},{"name":"thread","value":"3019-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_demo"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[]}],"tags":[]},"source":"858fc8a225486f1.json","parameterValues":[]}